#!/bin/bash
SCRIPT_DIR=$(cd $(dirname $0); pwd)

echo $SCRIPT_DIR

input_file=$SCRIPT_DIR."/input.txt"
output_file=$SCRIPT_DIR."/output.txt"

if [ -f "$file" ]
then
    echo "$file found." > $output_file.txt
else
    echo "$file not found." >$output_file.txt
fi
